### ISSUE TITLE
Module improvements

### ISSUE THREAD

**Issue by pi0** [Hrdtr/nuxt-appwrite#2]
Hi and thanks for nice nuxt module. Since adding to modules.nuxtjs.org, I've few improvement suggestions:

- Avoid using `require` in `plugin.js` and `sdk.js` and `utils.js` (this will ensure future compatibility with vite and nuxt3)
- Consider moving template related files (above) into a dedicated `runtime/` directory (this way it is clear what is added to runtime)

**Comment by Hrdtr** [comment]
Hello thanks for suggesting improvements here,  
please see the code snippet below

https://github.com/Hrdtr/nuxt-appwrite/blob/03cc23425955a75a494d6ecfd2e6434408c262a9/lib/plugin.js#L6

What if the \`\`\`require('cookie-universal')(ctx.req, ctx.res)\`\`\`  is used to get a cookie from a user request so that nuxt-appwrite knows the authentication status of that user on the server side?

**Comment by pi0** [comment]
You can do it like this: :)

```js
import cookieUniversal from 'cookie-universal'

export default (ctx, inject) => {
  const cookies = cookieUniversal (ctx.req, ctx.res)
}

```
