### ISSUE TITLE
nuxt3 compatibility

### ISSUE THREAD

**Issue by dennishelbig** [Hrdtr/nuxt-appwrite#211]
Hi, I was trying to use the module with a fresh install of nuxt3.
Unfortunately, I got errors while trying to set up the nuxt.config.ts file:

```
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  modules: [
   'nuxt-appwrite'
  ],
  appwrite: {
    endpoint: 'http://localhost/v1',
    project: '6235f703caf5c5814c16'
  }
})
```

The error says:

 Cannot set property $config of #<Object> which has only a getter at __vite_ssr_exports__.default (file://./.nuxt/dist/server/server.mjs:2265:15)  

...

Which raises my question: is nuxt-appwrite compatible with nuxt3?
Or am I doing something wrong?

**Comment by Elandrya2711** [comment]
Hi, i got the same problem today, and haven't found a solution yet. 
The https://modules.nuxtjs.org/?version=3.x site claims that it is ready for nuxt 3.

**Comment by Elandrya2711** [comment]
Getting the same Error when trying to use this in my fresh nuxt 3 project:
`[nuxt] [request error] Cannot set property $config of #<Object> which has only a getter
  at __vite_ssr_exports__.default (/D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:2929:15)
  at /D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:368:27
  at fn (/D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:388:27)
  at Object.callAsync (/D:/Coding/clean%20nuxt%203/node_modules/unctx/dist/index.mjs:41:19)
  at callWithNuxt (/D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:390:23)
  at applyPlugin (/D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:345:29)
  at Module.applyPlugins (/D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:355:11)
  at async createNuxtAppServer (/D:/Coding/clean%20nuxt%203/.nuxt/dist/server/server.mjs:46:7)
  at async Object.renderToString (/D:/Coding/clean%20nuxt%203/node_modules/vue-bundle-renderer/dist/index.mjs:252:19)
  at async /D:/Coding/clean%20nuxt%203/.nuxt/dev/index.mjs:478:20
`

Is there any ETA on when you will support nuxt 3?

**Comment by Hrdtr** [comment]
Nuxt3 support covered here:

https://github.com/YsarocK/nuxt-appwrite

**Comment by FranciscoKloganB** [comment]
**question:** if this package is no longer maintained, why don't we release it/change the name in order to allow other packages to be indexed on the official `nuxt/modules`?

I've noticed that there is some beef going on, but no one on the AppWrite nor Nuxt community stand to win by the existence of two packages competting with each other in unhealthy ways? One package has one maintainer, the other has two. One package is used by 22 repos, another is used by like a few only. When I look at both repos and see what's going on I don't have the courage to install either.

The way I see it there are few options that would benefit both:

- Release the repo name giving a chance of `nuxt3-appwrite` to thrive
- Find time to add full nuxt3 support thus removing the need for `nuxt3-appwrite` to exist
- Find time to collaborate with YsarocK, two (three) people think better than one and you are both likely to find more success by collaborating (actively - instead of sparsely)
- Add a *How to contribute* guide to your repository, so people can contribute to your repository directly without having to `fork` or create competing packages. This would possibly be the best solution has your current Nuxt2 users would not lose access to this repository due to a rename.

What do you think?
